export const BACKEND_URL = "http://localhost:5050/api/v1";

export const TODO_STATUS = {
  CREATED: "CREATED",
  TODO: "TODO",
  IN_PROGRESS: "IN PROGRESS",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
};

export const MEMBER_STATUS = {
  MEMBER: "MEMBER",
  PENDING: "PENDING",
  BLOCK: "BLOCK",
};

export const NOTIFICATION_TYPES = {
  MEMBER_REQUEST: "MEMBER_REQUEST",
  TODO_COMMENT_ADDED: "TODO_COMMENT_ADDED",
  TEAM_CHAT_MESSAGE: "TEAM_CHAT_MESSAGE",
  TODO_STATUS_CHANGED: "TODO_STATUS_CHANGED",
  GENERAL: "GENERAL",
};
